baseURL = 'https://www.tylonghuang.com/'
languageCode = 'en-us'
title = 'ðŸ² Long Hoang Nguyen'
theme = 'hugo-theme-shell'
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = false
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Long Nguyens Portfolio"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Gooey"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "lÏƒng.ngyn"
  pcName = "pm.me"
  workDir = "about"
  profile = "whoami.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  Hello and welcome! I am Long or é¾™.
  
  Some facts about me:
  - I am researching Accountable AI @ KIT
  - I am from Vietnam but live in Germany
  - I am speaking at least five languages
  
  - I value sustainable development
  - I value innovative technologies
  - I value modern privacy concerns
  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "contact"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["LinkedIn", "https://www.linkedin.com/in/long-hoang-nguyen-387171182/"],
    ["GitHub", "https://github.com/tylonghuang/"],
    ["Email", "mailto:long.ngyn@pm.me"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
